#!/usr/bin/env python3
"""Build the two published editions from the single source viewer in docs/.

One codebase, two audiences:

  all   — All-UQ public edition. Lean course browser, no AoL/GA layers.
          Self-contained (hosts all profile JSON + manifests). This is the
          edition ATLAS consumes and the one shared widely.

  uqbs  — UQBS edition (with the AoL/GA layers). Light: it ships only the
          viewer, the UQBS manifest and the overlays, and fetches the bulk
          profile data cross-origin from the All-UQ host (see --all-data-base).
          Drops into the team repo's uqbsld/ folder -> teach.business.uq.edu.au.

Outputs build/<edition>/ ready to commit to each edition's repo. Nothing here
touches the live site; deployment is a separate push from Sean's Mac.

Examples
--------
    # Quick structural build (no heavy profile copy) — used for verification
    python3 scraper/build_editions.py --skip-data

    # Real build for deployment
    python3 scraper/build_editions.py \
        --all-data-base https://uqsmitc6.github.io/uqbs-course-profiles-all \
        --all-repo  https://github.com/uqsmitc6/uqbs-course-profiles-all \
        --uqbs-repo https://github.com/UQ-Business-School/courses
"""
from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DOCS = REPO / "docs"
ASSETS = DOCS / "assets"

# Defaults — override on the command line once the repos/URLs are settled.
DEFAULT_ALL_DATA_BASE = "https://uqsmitc6.github.io/uqbs-course-profiles-all"
DEFAULT_ALL_REPO = "https://github.com/uqsmitc6/uqbs-course-profiles-all"
DEFAULT_UQBS_REPO = "https://github.com/UQ-Business-School/courses"

# Where the landing page's two buttons point (absolute, so the same splash works
# on either edition). Override on the command line once the URLs are settled.
DEFAULT_UQBS_URL = "http://teach.business.uq.edu.au/ld/uqbsld/profiles/business.html"
DEFAULT_ALL_URL = "https://uqsmitc6.github.io/uqbs-course-profiles/browse-all.html"

# Viewer files shared by every edition.
VIEWER_ASSETS = ["app.js", "styles.css"]

# Taxonomy/overlay files. AoL + GA overlays are UQBS-only.
OVERLAYS_COMMON = ["uqbs-programs.json", "teaching-periods.json", "lo-overrides.json"]
OVERLAYS_UQBS_ONLY = ["aol-status.json"]  # plus any ga*.json, matched dynamically


def site_config(edition: str, data_base: str, repo_url: str,
                uqbs_url: str, all_url: str, report_email: str) -> str:
    cfg = {
        "edition": edition,
        "dataBase": data_base,
        "repoUrl": repo_url,
        "uqbsUrl": uqbs_url,
        "allUrl": all_url,
        "reportEmail": report_email,
    }
    return (
        "/* Generated by scraper/build_editions.py — do not edit by hand. */\n"
        "window.SITE = " + json.dumps(cfg, indent=2) + ";\n"
    )


def reset_dir(root: Path) -> None:
    """Empty a build dir. Falls back to overwrite-in-place if deletes are
    blocked (some synced/mounted folders disallow unlink)."""
    if not root.exists():
        return
    try:
        shutil.rmtree(root)
    except (PermissionError, OSError) as e:
        print(f"  ! could not remove {root} ({e}); overwriting in place instead")


def copy(src: Path, dst: Path) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)


def copytree(src: Path, dst: Path) -> None:
    if not src.exists():
        print(f"  ! source missing, skipped: {src}")
        return
    shutil.copytree(src, dst, dirs_exist_ok=True, symlinks=False)


def dir_size_mb(path: Path) -> float:
    if not path.exists():
        return 0.0
    total = sum(f.stat().st_size for f in path.rglob("*") if f.is_file())
    return total / (1024 * 1024)


def build_all(out: Path, args) -> None:
    """All-UQ public edition: self-contained, no AoL/GA."""
    root = out / "all"
    reset_dir(root)
    (root / "assets").mkdir(parents=True, exist_ok=True)
    (root / "taxonomy").mkdir(parents=True, exist_ok=True)

    # Pages — front-door landing (index) + the all-UQ browser + course detail.
    copy(DOCS / "index.html", root / "index.html")          # landing splash
    copy(DOCS / "browse-all.html", root / "browse-all.html")  # the all-UQ browser
    copy(DOCS / "course.html", root / "course.html")

    # Viewer + config.
    for f in VIEWER_ASSETS:
        copy(ASSETS / f, root / "assets" / f)
    # This edition's own browser is a relative link (works on any host); the
    # other edition is absolute (cross-site).
    (root / "assets" / "site-config.js").write_text(
        site_config("all", "", args.all_repo, args.uqbs_url, "browse-all.html", args.report_email),
        encoding="utf-8",
    )

    # Manifests: all (primary) + UQBS (course-detail merge) + legacy (timeline).
    for m in ["manifest-all.json", "manifest.json", "manifest-legacy.json"]:
        copy(ASSETS / m, root / "assets" / m)

    # Overlays: common only — AoL/GA deliberately excluded.
    for f in OVERLAYS_COMMON:
        src = REPO / "taxonomy" / f
        if src.exists():
            copy(src, root / "taxonomy" / f)

    # Bulk data (heavy) — this edition hosts it.
    if not args.skip_data:
        print("  copying profiles/ and profiles-legacy/ (heavy)…")
        copytree(REPO / "profiles", root / "profiles")
        copytree(REPO / "profiles-legacy", root / "profiles-legacy")

    (root / "README.md").write_text(
        "# UQ Course Profile Viewer — All-UQ public edition\n\n"
        "Generated by `scraper/build_editions.py`. Do not edit in place; "
        "edit the source viewer in `docs/` of the main repo and rebuild.\n\n"
        "This edition is self-contained and is the data source for ATLAS and the "
        "UQBS edition (which fetches profile JSON from here).\n",
        encoding="utf-8",
    )
    _report("all", root, args.skip_data)


def build_uqbs(out: Path, args) -> None:
    """UQBS edition: AoL/GA on; bulk data fetched from the All-UQ host."""
    root = out / "uqbs"
    reset_dir(root)
    (root / "assets").mkdir(parents=True, exist_ok=True)
    (root / "taxonomy").mkdir(parents=True, exist_ok=True)

    data_base = "" if args.uqbs_self_contained else args.all_data_base

    # Pages — front-door landing (index) + the UQBS browser + detail/programs/AoL.
    for page in ["index.html", "business.html", "course.html", "program.html", "aol.html"]:
        copy(DOCS / page, root / page)

    # Viewer + config.
    for f in VIEWER_ASSETS:
        copy(ASSETS / f, root / "assets" / f)
    # This edition's own browser is a relative link (works on any host); the
    # other edition is absolute (cross-site).
    (root / "assets" / "site-config.js").write_text(
        site_config("uqbs", data_base, args.uqbs_repo, "business.html", args.all_url, args.report_email),
        encoding="utf-8",
    )

    # Primary manifest is always local. The big manifests are fetched from the
    # data base unless this edition is self-contained.
    copy(ASSETS / "manifest.json", root / "assets" / "manifest.json")
    if not data_base:
        for m in ["manifest-all.json", "manifest-legacy.json"]:
            copy(ASSETS / m, root / "assets" / m)

    # Overlays: common + UQBS-only (AoL, and any GA overlay when it exists).
    overlays = list(OVERLAYS_COMMON) + list(OVERLAYS_UQBS_ONLY)
    overlays += [p.name for p in (REPO / "taxonomy").glob("ga*.json")]
    for f in overlays:
        src = REPO / "taxonomy" / f
        if src.exists():
            copy(src, root / "taxonomy" / f)

    # Bulk data only when self-contained; otherwise it lives on the All-UQ host.
    if args.uqbs_self_contained and not args.skip_data:
        print("  copying profiles/ and profiles-legacy/ (heavy)…")
        copytree(REPO / "profiles", root / "profiles")
        copytree(REPO / "profiles-legacy", root / "profiles-legacy")

    note = (
        "self-contained" if data_base == "" else f"fetches bulk data from {data_base}"
    )
    (root / "README.md").write_text(
        "# UQBS Course Profile Viewer — UQBS edition\n\n"
        "Generated by `scraper/build_editions.py`. Do not edit in place; "
        "edit the source viewer in `docs/` of the main repo and rebuild.\n\n"
        f"AoL/GA layers on. Bulk data: {note}.\n",
        encoding="utf-8",
    )
    _report("uqbs", root, args.skip_data, data_base)


def _report(edition: str, root: Path, skip_data: bool, data_base: str | None = None) -> None:
    size = dir_size_mb(root)
    print(f"  built {edition}: {root}  (~{size:.1f} MB"
          + (", structure only" if skip_data else "") + ")")
    if data_base is not None:
        print(f"    data base: {data_base or '(self-contained)'}")


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Build the all-UQ and UQBS editions.")
    ap.add_argument("--out", default=str(REPO / "build"), help="output directory")
    ap.add_argument("--editions", default="all,uqbs",
                    help="comma list: all,uqbs (default both)")
    ap.add_argument("--all-data-base", default=DEFAULT_ALL_DATA_BASE,
                    help="root URL of the All-UQ host (UQBS edition fetches bulk data here)")
    ap.add_argument("--all-repo", default=DEFAULT_ALL_REPO, help="All-UQ Repository link")
    ap.add_argument("--uqbs-repo", default=DEFAULT_UQBS_REPO, help="UQBS Repository link")
    ap.add_argument("--uqbs-url", default=DEFAULT_UQBS_URL,
                    help="landing button target for the UQBS edition browser")
    ap.add_argument("--all-url", default=DEFAULT_ALL_URL,
                    help="landing button target for the All-UQ edition browser")
    ap.add_argument("--report-email", default="uqsmitc6@uq.edu.au",
                    help="recipient for the 'Report an error' button")
    ap.add_argument("--uqbs-self-contained", action="store_true",
                    help="UQBS edition carries its own profile data (no cross-origin fetch)")
    ap.add_argument("--skip-data", action="store_true",
                    help="don't copy the heavy profiles dirs (quick structural build)")
    args = ap.parse_args(argv)

    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    editions = [e.strip() for e in args.editions.split(",") if e.strip()]

    print(f"Building editions: {', '.join(editions)} -> {out}")
    if "all" in editions:
        build_all(out, args)
    if "uqbs" in editions:
        build_uqbs(out, args)
    print("Done.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
